language: node_js
env:
  global:
    - Hi5EisnW182Hdh2nsLUx1yU04MFQalW6KuYex3pOfmrZZR5yeYg4XkA05Ao9rm480VZtpH4uufjXGsxbOkD9z8CTUqDLVwrm+s3/A7DBjNuCo2hDuOpGEnHiBeJPdHIgSB/q+1tLsptPXmiAh1LpaOoXJji5pVH31fFenKGjtkn7UFaVl2s598CviOUsmzv9pfIPIoO7BH7mbt2oohWESFCsjstOfTUFSvgZddrMlglLZDWZ7817RPFhF6fcip0VVTSa9yUlg2GPiHGD/xaXxWsRkowEmk+Bb5z3Jv4mDGzBkOoNBt3jeKfczKqRiyu4oQ2uptNKT2U3GL0PEFersIQJ2hO2xnKiW00hratt/lb1LFmLZNeSgOzMhAaw56pSiw0NdNBfgG9EVghiGp2t8a+slenDPUb1PopPT/XtzItDoSFlhjaOpXm9dMXqLlV86+nHSmHBJ1UqKL+FAdgLl7arRMDodTGQWUNYbt2EKa5Jq8iSClhPaxYM6G+4o+aNBCCgbwXPY4BO2A8Aa7GkcDLZIi6D2Ro0xTzf2JEv4SL9sLRXPF2qfxuazJ0MIDAgMtGQAXNMgdQUkCe0KQ6VgdMGm4SN4vaN4HyA8DY4XKQgyS07+1Bo1znFZp7KZfkuf9XPnwfA6APAMQC4No4GCK4a9EgiuexutTPBUNuYPJI=
before_script:
  - npm run setup
  - npm run build
script:
  - npm run test:unit
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "@btrobots/core.tgz"
    skip_cleanup: true
    on:
      tags: true
#  - provider: npm
#    skip_cleanup: true
#    email: "docherty315@gmail.com"
#    api_key: $NPM_TOKEN
#    on:
#      tags: true